baseurl                  = "https://dishpanda.github.io/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "rahul deshpande"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "&copy; rahul s deshpande 2020"

# Metadata for Open Graph and Twitter
    description          = "my name's rahul. nice to meet you!"               # Max 160 characters show in search results
    images               = ["tn.jpg"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "rahul deshpande"

[[params.mainMenu]]
    link = "/about"
    text = "who is rahul?"

[[params.mainMenu]]
    link = "/posts"
    text = "blog"

[[params.mainMenu]]
    link = "/bw-portfolio"
    text = "black and white"

[imaging]
    quality = 75